- Jenkinsfile.publish
> Setting up Continuous Deployment

- Client.xcodeproj/project.pbxproj
- Client/Frontend/Browser/Tab.swift
- Client/Frontend/Widgets/AutocompleteTextField.swift
- Cliqz/Extensions/TabExtension.swift
- Cliqz/Privacy/BlockListManager.swift
- Cliqz/Privacy/UI/GhosteryButton.swift
- Cliqz/React Components/Engine.swift
- Cliqz/React Components/Modules/BrowserActions.swift
- Cliqz/React Components/Modules/GeoLocationBridge.m
- Cliqz/React Components/Modules/Geolocation.swift
- Cliqz/React Components/Modules/PermissionManagerModule.swift
- Cliqz/React Components/Modules/PermissionManagerModuleBridge.m
- Cliqz/Search/CliqzSearchViewController.swift
- Cliqz/Services/LocationManager.swift
- Cliqz/URLBar/CliqzURLBar.swift
- package.json
> New Mixer Integration + Small fixes to Antitracking 

- package.json
> new extension

- Jenkinsfile.publish
Changing to using box with macOS HighSierra and Xcode 9.3
> Use box with HighSierra and Xcode-9.3

- Jenkinsfile.nightly
> IB2-174 Schedule nightly job to submit new version to TF

- Cliqz/React Components/Engine.swift
- Cliqz/React Components/Modules/BrowserActions.swift
- Cliqz/React Components/Modules/BrowserActionsBridge.m
- Cliqz/Search/CliqzSearchViewController.swift
- Cliqz/URLBar/CliqzURLBar.swift
- package.json
>  Use extension version 1.28.1 prerelease 2

- Jenkinsfile.nightly
> Add Clean Up and Jira Stage

- Client/Frontend/Browser/BrowserTrayAnimators.swift
- Client/Frontend/Browser/TabTrayController.swift
> Small fixes

- Jenkinsfile.nightly
- Jenkinsfile.publish
> IB2-213 Configure nightly and publish job with new configurations

- Client/Frontend/Browser/TabTrayController.swift
- Cliqz/HomePanel/Freshtab/FreshtabViewController.swift
- Cliqz/HomePanel/Freshtab/TopSites/TopSitesViewController.swift
- Cliqz/Privacy/AdAndTrackingProtection/BlockListManager/Operations/ApplyDefaultsOperation.swift
- Cliqz/Privacy/AdAndTrackingProtection/BlockListManager/Operations/PopulateBlockedTrackersOperation.swift
- Cliqz/Privacy/AdAndTrackingProtection/TrackingManagement/TrackerListApp.swift
- Cliqz/React Components/Modules/JSBridge.swift
- Cliqz/React Components/Modules/SubscriptionModule.swift
- Cliqz/React Components/Modules/SubscriptionModuleBridge.m
- Cliqz/Storage/GhosteryMigration/GhosteryMigrationManager.swift
- Cliqz/Storage/PrivacyStore/TrackerStateStore.swift
- Cliqz/Telemetry/TelemetryHelper.swift
> Telemetry Fixes + Subscription removal + SettingsButton for Sharath

- Jenkinsfile
Building the App using the -DAUTOMATION flag; for running tests
> Jenkinsfile Change

- Client.xcodeproj/project.pbxproj
- Cliqz/Extensions/ArrayExtensions.swift
- Cliqz/Extensions/BrowserViewController/Privacy.swift
- Cliqz/HomePanel/CliqzHomePanelViewController.swift
- Cliqz/HomePanel/Freshtab/FreshtabViewController.swift
- Cliqz/HomePanel/Freshtab/News/NewsViewController.swift
- Cliqz/Privacy/AdAndTrackingProtection/TrackingManagement/PageTrackersFound.swift
- Cliqz/Privacy/AdAndTrackingProtection/TrackingManagement/TrackerList.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDataSource.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDelegate.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterViewController.swift
- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
- Cliqz/Privacy/UI/ControlCenter/TrackersController.swift
> Visual fixes + CC optimizations

- Cliqz/HomePanel/Freshtab/FreshtabViewController.swift
- Cliqz/HomePanel/Freshtab/News/NewsViewController.swift
- Cliqz/HomePanel/Freshtab/TopSites/TopSitesViewController.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDelegate.swift
- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
> Fix Freshtab Bugs + CC Bugs

- Client/Application/AppDelegate.swift
- Client/Frontend/Browser/BrowserViewController.swift
- Cliqz/Extensions/BrowserViewController/Privacy.swift
- Cliqz/HomePanel/CliqzHomePanelViewController.swift
- Cliqz/Intro/CliqzIntroViewController.swift
- Cliqz/Privacy/AdAndTrackingProtection/BlockListManager/Operations/PopulateBlockedTrackersOperation.swift
- Cliqz/Privacy/AdAndTrackingProtection/TrackingManagement/TrackerList.swift
- Cliqz/Privacy/AdAndTrackingProtection/TrackingManagement/TrackerListApp.swift
- Cliqz/Privacy/AdAndTrackingProtection/URLInterceptor.swift
- Cliqz/Privacy/AdAndTrackingProtection/UserPreferences.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDataSource.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDelegate.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterViewController.swift
- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
- Cliqz/Privacy/UI/ControlCenter/TrackersController.swift
- Cliqz/Privacy/UI/GhosteryButton.swift
- Cliqz/Resources/CliqzStrings.swift
- Cliqz/Search/CliqzSearchViewController.swift
- Cliqz/Storage/PrivacyStore/DomainStore.swift
- Cliqz/Storage/PrivacyStore/TrackerStateStore.swift
- Cliqz/URLBar/CliqzURLBar.swift
> Fixes + Undo + Search BG image + Trust/Untrust

- Client/Frontend/Browser/BrowserViewController.swift
- Cliqz/Intro/CliqzIntroViewController.swift
- Cliqz/Privacy/AdAndTrackingProtection/UserPreferences.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDataSource.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDelegate.swift
- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
- Cliqz/Privacy/UI/ControlCenter/TrackersController.swift
- Cliqz/Privacy/UI/GhosteryButton.swift
- Cliqz/Resources/CliqzStrings.swift
- Cliqz/Settings/CliqzAppSettingsTableViewController.swift
- Cliqz/URLBar/CliqzURLBar.swift
> Ghostie Fixes + Control Center + Other small fixes

- Cliqz/Extensions/ArrayExtensions.swift
- Cliqz/Privacy/AdAndTrackingProtection/BlockListManager/Operations/ApplyDefaultsOperation.swift
- Cliqz/Privacy/AdAndTrackingProtection/TrackingManagement/TrackerListApp.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDataSource.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDelegate.swift
- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
- Cliqz/Privacy/UI/ControlCenter/TrackersController.swift
- Cliqz/Storage/GhosteryMigration/GhosteryMigrationManager.swift
- Cliqz/Storage/PrivacyStore/DomainStore.swift
- Cliqz/Storage/PrivacyStore/TrackerStateStore.swift
Refactored the Database Layer to make writing to the database faster. I also made some changes that enforce correctness (the way domain lists are changed).
> Speed improvement + Smaller Bug fixes

- package.json
This version has cleaning of antitracking dependencies and
exporting of getTrackerDetails action to native
> Update extension version to 3.28.2

- Client.xcodeproj/project.pbxproj
- Cliqz/Extensions/BrowserViewController/Privacy.swift
- Cliqz/Privacy/AdAndTrackingProtection/BlockListManager/Operations/UpdateOperation.swift
- Cliqz/Privacy/LoadingNotificationManager.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDelegate.swift
- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
- Cliqz/Privacy/UI/ControlCenter/TrackersController.swift
- Cliqz/Services/CustomSimpleToast.swift
- Cliqz/Storage/PrivacyStore/TrackerStateStore.swift
> Simplified TrackerStateStore and CC Bug fixes

- Jenkinsfile.nightly
@naira-cliqz, @mahmoud-cliqz 
Ensuring that jira transistions only occur after previous stages are successful. Also better reporting on ticket transistions. Adding changelogs since last successful build in preference to changelogs of current build.
> Improve error handling for nightly job

- package.json
> Upgrade extension to 1.29.0_mobile_pre1

- Jenkinsfile.nightly
- Jenkinsfile.publish
> Fix for publishing apps

- Jenkinsfile.nightly
- Jenkinsfile.publish
> Add Install Sentry-cli

- Jenkinsfile.nightly
- Jenkinsfile.publish
> Fix nightly and publish job

- package.json
This upgrade includes:
- Read app channel from native
> Upgrade extension to 1.29.1_mobile_pre3

- Jenkinsfile
> Remove Cleanup of Carthage, Pods and Node Modules

- Jenkinsfile.publish
> IB2-376 Modify publish job to work with Anolysis channels

- Jenkinsfile.nightly
- Jenkinsfile.publish
@mahmoud-cliqz To stop the installation of sentry making the builds fail.
> Move installing of sentry-cli to beginning

- Client/Application/AppDelegate.swift
- Cliqz/Privacy/AdAndTrackingProtection/BlockingCoordinator.swift
- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
- Cliqz/Privacy/UI/ControlCenter/TrackersController.swift
- Cliqz/Storage/PrivacyStore/DomainStore.swift
> Fixes + Prep for Adblocker options

- Cliqz/Intro/CliqzIntroViewController.swift
- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
> Bug + Accessibility Identifiers

- Cliqz/Intro/CliqzIntroViewController.swift
- package-lock.json
> Fixes Onboarding

- Client/Frontend/Browser/BrowserViewController/BrowserViewController+DownloadQueueDelegate.swift
- Cliqz/Intro/CliqzIntroViewController.swift
Remove Downloads Button: I tried to open it in Files. I cannot find any doc on it. I tried a couple of ideas but both failed. 
Fix Start Browsing title issue: The title was cut in french on iPhone 7.
> Remove Downloads Button + Fix Start Browsing title issue

- Cliqz/React Components/Modules/NativeDrawable.m
- package-lock.json
- package.json
> Upgdate extension + NativeDrawables

- Jenkinsfile.nightly
- Jenkinsfile.publish
- fastlane/Fastfile
- Removed bootstrap.sh and added the scripts to fastlane.
-- 'fastlane prepare' does the Carthage bootstrap, Pod Install, npm Install and npm run Build.
-- 'fastlane clearCache' clears the node_modules and Cache & lock files for Pods & Carthage.
- Also removed 'yarn' and using only npm install instead.
> Jenkinsfile and Fastlane changes for Nightly and Release

- package-lock.json
- package.json
This Upgrade incluedes:
- fix for different search engine serp pages showing in history
> Upgrade extension version to 3.30.2

- Jenkinsfile
- Jenkinsfile.nightly
- Jenkinsfile.publish
- fastlane/Fastfile
Using virtual machine created with virtual box provider.
Modify pod install step to find new dependencies 
@timotei-cliqz
> Update pod install and use new VM for Nightly and Publish jobs

- Client.xcodeproj/project.pbxproj
- Cliqz/HomePanel/VPN/VPNButton.swift
- Cliqz/React Components/Modules/Crypto.swift
- Cliqz/Resources/Cliqz.xcassets/AppIcon_Cliqz.appiconset/Contents.json
- Cliqz/Resources/Cliqz.xcassets/AppIcon_Paid.appiconset/Contents.json
- Podfile
> Fixed build issues on Xcode10

- package.json
*Thank you for submitting a pull request, your contributions are greatly appreciated!*
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.
If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.
> update extensions to 3.31.1

- Client.xcodeproj/project.pbxproj
- Client/Frontend/Browser/Tab.swift
- Cliqz/Extensions/TabExtension.swift
- Cliqz/Privacy/AdAndTrackingProtection/URLInterceptor.swift
- Cliqz/Privacy/Assets/postload.js
- Cliqz/Privacy/Assets/preload.js
- Cliqz/Privacy/Assets/timing.js
- Cliqz/Privacy/UI/ControlCenter/PaidControlCenter/CCDataSource.swift
- Cliqz/Privacy/UI/ControlCenter/PaidControlCenter/CCWidget.swift
- Cliqz/Privacy/UI/ControlCenter/PaidControlCenter/PaidControlCenterViewController.swift
- Shared/UserAgent.swift
> Data Integration Dashboard

- Jenkinsfile
> Open Source Tests

- Client/Application/AppDelegate.swift
- Client/Frontend/Browser/Tab.swift
- Cliqz/Extensions/BrowserViewController/Privacy.swift
- Cliqz/Extensions/ColorExtension.swift
- Cliqz/Extensions/TabExtension.swift
- Cliqz/HomePanel/CliqzHomePanels.swift
- Cliqz/HomePanel/VPN/Keychain.swift
- Cliqz/HomePanel/VPN/VPNButton.swift
- Cliqz/HomePanel/VPN/VPNCountryController.swift
- Cliqz/HomePanel/VPN/VPNViewController.swift
- Cliqz/Intro/CliqzIntroViewController.swift
- Cliqz/Privacy/AdAndTrackingProtection/BlockListManager/Identifiers.swift
- Cliqz/Privacy/AdAndTrackingProtection/BlockListManager/Operations/ApplyDefaultsOperation.swift
- Cliqz/Privacy/AdAndTrackingProtection/BlockingCoordinator.swift
- Cliqz/Privacy/AdAndTrackingProtection/TrackingManagement/TrackerList.swift
- Cliqz/Privacy/AdAndTrackingProtection/UserPreferences.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDataSource.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterDelegate.swift
- Cliqz/Privacy/UI/ControlCenter/ControlCenterViewController.swift
- Cliqz/Privacy/UI/ControlCenter/GlobalTrackersViewController.swift
- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
- Cliqz/Privacy/UI/ControlCenter/PaidControlCenter/CCWidget.swift
- Cliqz/Privacy/UI/ControlCenter/PaidControlCenter/PaidControlCenterViewController.swift
- Cliqz/Privacy/UI/ControlCenter/TrackersController.swift
- Cliqz/Settings/CliqzAppSettingsOptions.swift
- Cliqz/Settings/Custom Settings/AdBlockerSettingsTableViewController.swift
- UnitTests/LogoLoaderTests.swift
> Controls + VPN

- Client.xcodeproj/project.pbxproj
- Cliqz/Authentication/EmailVerificationViewController.swift
- Cliqz/Authentication/RegistrationConfirmationViewController.swift
- Cliqz/Authentication/RegistrationViewController.swift
- Cliqz/HomePanel/VPN/VPNButton.swift
- Cliqz/HomePanel/VPN/VPNCountryController.swift
- Cliqz/HomePanel/VPN/VPNViewController.swift
- Cliqz/Privacy/UI/ControlCenter/PaidControlCenter/CCDataSource.swift
- Cliqz/Privacy/UI/ControlCenter/PaidControlCenter/CCWidget.swift
- Cliqz/Privacy/UI/ControlCenter/PaidControlCenter/PaidControlCenterViewController.swift
- package-lock.json
Updated localized strings related to Lumen (Dashboard, VPN, Authentication)
> Lumen Browser Fixes

- Cliqz/HomePanel/VPN/VPNViewController.swift
> VPN Bug fix

- Jenkinsfile.publish
- LumenJenkinsfile.nightly
> Configure Jenkins for lumen nightly 

- fastlane/actions/import_cliqz_localizations.rb
@naira-cliqz 
@sharath-cliqz 
http://magrathea:8080/job/Mobile/job/cliqz-ios/job/nightlyLumen/12/
> Remove logs when adding localization

- package.json
> Updated extension version

- Jenkinsfile.nightly
- Jenkinsfile.publish
- LumenJenkinsfile.nightly
@mahmoud-cliqz @naira-cliqz 
Please take a look, I would like to remove all old VM's to clear space on the build server.
> Use box with xcode10.1 in publish and nightly jobs

- Jenkinsfile.publish
@mahmoud-cliqz 
I had to recreate the virtual machine that we reuse for app store publish jobs
> Update virtual machine id

- Jenkinsfile.nightly
- Jenkinsfile.publish
- LumenJenkinsfile.nightly
@mahmoud-cliqz Some changes that I forgot to add
> Virtualbox

- Jenkinsfile.nightly
- Jenkinsfile.publish
- LumenJenkinsfile.nightly
> Fix cpu assignment

- Cliqz/Privacy/AdAndTrackingProtection/UserPreferences.swift
*Thank you for submitting a pull request, your contributions are greatly appreciated!*
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.
If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.
>  IP-462: set lumen.protection.isEnabled on toggling

- Jenkinsfile.nightly
- Jenkinsfile.publish
> Add timeout and Faliure email notification

- Jenkinsfile.nightly
- fastlane/Fastfile
> Add nightly builds on production

- fastlane/Fastfile
> Fix Environment taken by Fastlane

- Cliqz/Resources/Paid.xcassets/Intro/lumen-Dashboard.imageset/Contents.json
- Cliqz/Upgrade&Payment/Cotroller/PromoCodesManager.swift
- reverted back lost onboarding icon
- made promo codes case insensitive
> [IP-559] [Onboarding] First screen is missing

- fastlane/Fastfile
> Add removal of old localization files to importLocalizations lane

- Client.xcodeproj/xcshareddata/xcschemes/Lumen Debug.xcscheme
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/ContextMenuHelper.swift
- fix by firefox https://github.com/brave/brave-ios/pull/1016/files
> [IP-396] [Core] "Open in new tab" is missing from context menu

- Cliqz/HomePanel/VPN/VPN.swift
- Cliqz/HomePanel/VPN/VPNEndPointManager.swift
- Cliqz/HomePanel/VPN/VPNViewController.swift
- Cliqz/Upgrade&Payment/Services/IAPService.swift
- Cliqz/Upgrade&Payment/Services/RevenueCatService.swift
- Cliqz/Upgrade&Payment/View/UpgradeViews/BaseUpgradeViewController.swift
- Cliqz/Upgrade&Payment/View/UpgradeViews/UpgradLumenViewController.swift
> [IP-624] [Subscriptions UI] Loading indicator after clicking on subscribe

- fastlane/Fastfile
> Use updated sentry project names

- Jenkinsfile.nightly
- Jenkinsfile.publish
- fastlane/Fastfile
Change Cliqz Version Number to 2.0.0, use bundle-cliqz and setup cliqz build on tags
@naira-cliqz
> Change Cliqz Version Number to 2.0.0 + other changes

- Cliqz/HomePanel/VPN/VPNCountrySelectionController.swift
> [IP-535] Do not show error messages after VPN Country is selected

- Cliqz/HomePanel/VPN/VPNCountrySelectionController.swift
> [IP-535] Inhibit VPN Error Message

- Client.xcodeproj/project.pbxproj
- Client/Configuration/Cliqz.xcconfig
- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Browser/TabToolbar.swift
- Cliqz/Extensions/BrowserViewController/BrowserViewController+CliqzMigration.swift
- Cliqz/Settings/CliqzAppSettingsOptions.swift
- Cliqz/Settings/CliqzAppSettingsTableViewController.swift
- Cliqz/Settings/Custom Settings/SendUsageDataTableViewController.swift
- Cliqz/Share Menu/ShareExtensionActivities.swift
- Cliqz/Theme/GhosteryDarkTheme.swift
- Podfile.lock
> UI and functional fixes for Cliqz

- cliqz.js
Deletes `AsyncStorage` data used by the legacy Cliqz browser.
> Prune legacy data from Cliqz browser

- package.json
Reverts ghostery/browser-ios#372
> Revert "Copy lumen assets"

- Client/Configuration/Cliqz.xcconfig
> [IB-1916] Update Bundle Display Name for Cliqz

- Client/Frontend/Browser/BrowserViewController.swift
- Cliqz/Intro/CliqzIntroViewController.swift
> [IB-1891]  Save the preference value that the intro has been seen 

- Cliqz/Privacy/UI/ControlCenter/OverviewViewController.swift
> [IB-1923] Revert Previous Fix

- Client/Frontend/Browser/BrowserViewController.swift
- Cliqz/Extensions/BrowserViewController/BrowserViewController+CliqzMigration.swift
- Cliqz/Services/LocalDataStore.swift
> [IB-1891] Load first tab in viewDidAppear

- CliqzJenkinsfile.nightly
- Jenkinsfile.nightly
- Jenkinsfile.publish
- LumenJenkinsfile.nightly
> Build Faliure if timeout is reached

- cliqz.js
- package-lock.json
- package.json
Reworking communication between native and react-native to follow changes introduced by #394
> [cliqz] rework communication

- Client/Frontend/Widgets/AutocompleteTextField.swift
- Cliqz/Resources/Common.xcassets/downloadVideo.imageset/Contents.json
- Cliqz/URLBar/CliqzTabLocationView.swift
- cliqz.js
- lumen.js
- fixed URL bar jumping issue
- fixed missing dashboard info
> [IP-673] [IP-674] [Dashboard] counts is always 0

- Client/Frontend/Browser/TabTrayController.swift
- Cliqz/Tab Tray/CliqzPrivateModeButton.swift
- Cliqz/URLBar/CliqzTabLocationView.swift
- fixed private button position
- fixed download button color in private mode
> UI Enhancements for Private Mode

- Cliqz/Search/CliqzSearchViewController.swift
- added fallback mechanism to encode URL's if needed
> Fixed some search results not opening issue

- Cartfile
- Cliqz/Extensions/BrowserDBExtensions.swift
- Migration will only be run once
- Migration will be run inside a single transaction
> Improve Database migration for old Cliqz Database

- Client/Frontend/Browser/BrowserTrayAnimators.swift
- Client/Frontend/Browser/TabTrayController+KeyCommands.swift
- Client/Frontend/Browser/TabTrayController.swift
> Tabs: remove search UI

- package-lock.json
- package.json
Bumping the version with hope to deal with Cliqz crashes.
> React Native version bump

- Client/Frontend/Browser/BrowserViewController.swift
- Client/Frontend/Widgets/PhotonActionSheet.swift
- Cliqz/Theme/GhosteryDarkTheme.swift
> Long press on urlbar theme colors

- Cliqz/MyOffrz/OffrzOnboardingView.swift
- Cliqz/Settings/CliqzAppSettingsOptions.swift
> Fix Ghostery Rewards Wording
